version: 2
updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: monthly
    groups:
      non-majors:
        update-types:
          - "patch"
          - "minor"
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: monthly
    groups:
      non-majors:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: docker
    directory: /tools/refactoringminer
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /tools/refdiff
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
