version: '3.8'

services:
  frontend:
    container_name: rs-frontend
    restart: always
    image: ghcr.io/salab/refsearch-frontend:master
    build:
     context: .
     dockerfile: ./frontend.Dockerfile
    ports:
      - "8080:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  backend:
    container_name: rs-backend
    restart: always
    image: ghcr.io/salab/refsearch-backend:master
    build:
      context: .
      dockerfile: ./backend.Dockerfile
      target: api-runner
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGODB_USER: root
      MONGODB_PASSWORD: password
      MONGODB_HOST: rs-mongo
      MONGODB_PORT: 27017
    volumes:
      - ./data:/data

  mongodb:
    container_name: rs-mongo
    restart: always
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongodb:/data/db
    deploy:
      resources:
        limits:
          memory: 2G

  rminer:
    container_name: rs-rminer
    restart: always
    image: ghcr.io/salab/refsearch-rminer:master
    build:
      context: ./tools/refactoringminer
    command: ["serve", "--port", "3000"]
    expose:
      - "3000"
    volumes:
      - ./data:/data

  refdiff:
    container_name: rs-refdiff
    restart: always
    image: ghcr.io/salab/refsearch-refdiff:master
    build:
      context: ./tools/refdiff
    command: ["serve", "--port", "3000"]
    expose:
      - "3000"
    volumes:
      - ./data:/data

  runner1:
    container_name: rs-runner-1
    restart: always
    image: ghcr.io/salab/refsearch-runner:master
    build:
      context: .
      dockerfile: ./backend.Dockerfile
      target: job-runner
    environment:
      RUNNER_ID: local-1
      MONGODB_USER: root
      MONGODB_PASSWORD: password
      MONGODB_HOST: rs-mongo
      MONGODB_PORT: 27017
      DATA_DIR: /data
      RMINER_HOST: rminer
      RMINER_PORT: 3000
      RMINER_BASE_PATH: /data/repos
      REFDIFF_HOST: refdiff
      REFDIFF_PORT: 3000
      REFDIFF_BASE_PATH: /data/repos
    volumes:
      - ./data:/data

volumes:
  caddy_data:
  caddy_config:
