RM_VERSION=2.3.2

.PHONY: rminer
rminer:
	docker build -t ghcr.io/salab/refsearch-rminer:master refactoringminer

.PHONY: refdiff
refdiff:
	docker build -t ghcr.io/salab/refsearch-refdiff:master refdiff
