name: Build RefSearch Images

on:
  push:
    branches:
      - master

jobs:
  refsearch-backend:
    name: Build RS backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: salab
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./backend.Dockerfile
          target: api-runner
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/salab/refsearch-backend:master
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Delete all containers from package without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: refsearch-backend
          untagged_only: true
          owner_type: org

  refsearch-runner:
    name: Build RS runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: salab
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./backend.Dockerfile
          target: job-runner
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/salab/refsearch-runner:master
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Delete all containers from package without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: refsearch-runner
          untagged_only: true
          owner_type: org

  refsearch-frontend:
    name: Build RS frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: salab
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: ./frontend.Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/salab/refsearch-frontend:master
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Delete all containers from package without tags
        uses: Chizkiyahu/delete-untagged-ghcr-action@v2
        with:
          token: ${{ secrets.PAT }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          package_name: refsearch-frontend
          untagged_only: true
          owner_type: org
