name: Build Tool Images

on:
  push:
    branches:
      - master
    paths:
      - 'tools/**'

jobs:
  rminer:
    name: Build RMiner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: salab
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./tools/refactoringminer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/salab/refsearch-rminer:master
          cache-from: type=gha
          cache-to: type=gha,mode=max

  refdiff:
    name: Build RefDiff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: salab
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./tools/refdiff
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/salab/refsearch-refdiff:master
          cache-from: type=gha
          cache-to: type=gha,mode=max
